### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by ahhsia** [compuphase/KiCad-Librarian#5]
Using wxmac-3.0.2 and wxpython-3.0.2, I get this compiling error.
Should I be using a different version of wxwidgets?

[ 61%] Building CXX object CMakeFiles/kicadlibrarian.dir/libraryfunctions.cpp.o
/Users/x/dotcad/kicad/tools/KiCad-Librarian/src/libraryfunctions.cpp:1651:33: warning:
      comparison of unsigned expression < 0 is always false [-Wtautological-compare]
        if (footprint_attr_line < 0 && type != VER_INVALID) {
            ~~~~~~~~~~~~~~~~~~~ ^ ~
1 warning generated.
[ 66%] Building CXX object CMakeFiles/kicadlibrarian.dir/pdfreport.cpp.o
/Users/x/dotcad/kicad/tools/KiCad-Librarian/src/pdfreport.cpp:804:23: error: no matching
      constructor for initialization of 'wxSortedArrayString'
  wxSortedArrayString SortedIndex(CompareFootprint);
                      ^           ~~~~~~~~~~~~~~~~
/Users/x/.m3/envs/kicad/include/wx-3.0/wx/arrstr.h:377:24: note: candidate constructor
      (the implicit copy constructor) not viable: no known conversion from 'int (const wxString &,
      const wxString &)' to 'const wxSortedArrayString' for 1st argument
class WXDLLIMPEXP_BASE wxSortedArrayString : public wxArrayString
                       ^
/Users/x/.m3/envs/kicad/include/wx-3.0/wx/arrstr.h:382:3: note: candidate constructor not
      viable: no known conversion from 'int (const wxString &, const wxString &)' to
      'const wxArrayString' for 1st argument
  wxSortedArrayString(const wxArrayString& array) : wxArrayString(true)
  ^
/Users/x/.m3/envs/kicad/include/wx-3.0/wx/arrstr.h:380:3: note: candidate constructor not
      viable: requires 0 arguments, but 1 was provided
  wxSortedArrayString() : wxArrayString(true)
  ^
1 error generated.
make[2]: *** [CMakeFiles/kicadlibrarian.dir/pdfreport.cpp.o] Error 1
make[1]: *** [CMakeFiles/kicadlibrarian.dir/all] Error 2
make: *** [all] Error 2

**Comment by melak** [comment]
Can you try this?
```diff
diff --git a/src/pdfreport.cpp b/src/pdfreport.cpp
index 11d68e6..25c97d5 100644
--- a/src/pdfreport.cpp
+++ b/src/pdfreport.cpp
@@ -800,14 +800,16 @@ bool PdfReport::FootprintReport(wxWindow* parent, const wxString& library, const
     DryRun=!DryRun;
   } while (!DryRun);
 
-  /* sort the index */
-  wxSortedArrayString SortedIndex(CompareFootprint);
+  wxArrayString SortedIndex;
   for (wxStringToStringHashMap::iterator iter = FootprintIndex.begin(); iter != FootprintIndex.end(); iter++) {
     wxString line = iter->first + wxT(" : ") + iter->second;
     SortedIndex.Add(line);
   }
   FootprintIndex.clear();
 
+  /* sort the index */
+  SortedIndex.Sort(CompareFootprint);
+
   /* print the index */
   progress.Update(++progresspos,wxT("Generating the index"));
   DryRun=false;
```

I am not at the moment able to actually verify whether this actually works the same (or at all for that matter, although it should), but it compiles with 3.0.2.

**Comment by ahhsia** [comment]
Looks like that patch fixes the compile error for use with wxmac-3.0.2.
Thanks!

It now completes compilation but now gives a linker error, but I suspect weirdness with mac build system's confusion of libstdc++ and libc++:

[100%] Linking CXX executable kicadlibrarian
Undefined symbols for architecture x86_64:
  "_SyStrncmp", referenced from:
      _unixOpen in unqlite.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [kicadlibrarian] Error 1
make[1]: *** [CMakeFiles/kicadlibrarian.dir/all] Error 2
make: *** [all] Error 2

**Comment by melak** [comment]
This I can't help with I'm afraid :(

**Comment by Gasman2014** [comment]
Did this get resolved by @ahhsia as I am experiencing similar problems. I am able to run this using wine in MacOS BUT there are some menu dropdown problems.
![screen shot 2017-07-11 at 15 02 06](https://user-images.githubusercontent.com/8401593/28072134-fee6ebea-6649-11e7-886e-3ac91c2944a8.png)

**Comment by compuphase** [comment]
@melak: thanks for the patch. I am using wxWidgets 3.1. So I must have missed this issue.

@ ahhsia: the linker error is unrelated to the patch. That (linker) error is due to unqlite, which KicadLibrarian uses to cache footprint data for quick searching & filtering. Please get the latest unqlite files from https://github.com/symisc/unqlite. You only need unqlite.c and unqlite.h.
